// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Acceptance
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GetTicketsFeature : Xunit.IClassFixture<GetTicketsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GetTickets.feature"
#line hidden
        
        public GetTicketsFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GetTickets", "\tIn order to see tickets for an events\r\n\tAs api consumer \r\n\tI want to be retrieve" +
                    " tickets by event ID", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(GetTicketsFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Current event with tickets")]
        [Xunit.TraitAttribute("FeatureTitle", "GetTickets")]
        [Xunit.TraitAttribute("Description", "Current event with tickets")]
        [Xunit.TraitAttribute("Category", "Ticket")]
        public virtual void CurrentEventWithTickets()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Current event with tickets", new string[] {
                        "Ticket"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "Name",
                        "On Sale Date",
                        "Doors Open Date",
                        "Event Start Date",
                        "Event End Date"});
            table1.AddRow(new string[] {
                        "1",
                        "Annual Charity Event",
                        "30 days ago",
                        "4 days 13 hours from now",
                        "5 days 14 hours from now",
                        "5 days 17 hours from now"});
#line 8
 testRunner.Given("the following event(s) exist", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Event ID",
                        "Name",
                        "Price",
                        "Quantity Available"});
            table2.AddRow(new string[] {
                        "1",
                        "General Adminission",
                        "10.00",
                        "500"});
            table2.AddRow(new string[] {
                        "1",
                        "VIP",
                        "30.00",
                        "100"});
#line 11
 testRunner.And("the following tickets are available", ((string)(null)), table2, "And ");
#line 15
 testRunner.When("I make a call to \"http://localhost:53735/api/Tickets/1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("the response status code is 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.And("the content type is \"application/json\" and charset \"utf-8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "Name",
                        "Price"});
            table3.AddRow(new string[] {
                        "1",
                        "General Adminission",
                        "10.00"});
            table3.AddRow(new string[] {
                        "2",
                        "VIP",
                        "30.00"});
#line 18
 testRunner.And("the response should include the following tickets", ((string)(null)), table3, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GetTicketsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GetTicketsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
